[package]
name = "day18"
version = "0.1.0"
authors = ["Florian Rohm <rohm.florian@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1"
lazy_static = "1.4.0"