[package]
name = "day7"
version = "0.1.0"
authors = ["Florian Rohm <rohm.florian@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
lazy_static = "1.4.0"
multimap = "0.8.2"