[package]
name = "get-input"
version = "0.1.0"
authors = ["Florian Rohm <rohm.florian@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
